git:
  depth: 10
notifications:
  email: false

sudo: false
language: cpp
compiler: clang
os:
  - linux
  - osx
env:
  - TARGET_ARCH=x64

addons:
  apt:
    packages:
    - libdbus-glib-1-dev
    - libgconf2-dev
    - libgnome-keyring-dev
    - libgtk2.0-dev
    - libnotify-dev
    - libnss3-dev
    - gcc-multilib
    - g++-multilib
    - libc6-dev-armhf-cross
    - g++4.6-arm-linux-gnueabihf

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32

script: './script/cibuild'

branches:
  only:
    - master
