# The config expects the following environment variables to be set:
#  - "GN_CONFIG" Build type. One of {'testing', 'release'}.
#  - "GN_EXTRA_ARGS" Additional gn arguments for a build config,
#      e.g. 'target_cpu="x86"' to build for a 32bit platform.
#      https://gn.googlesource.com/gn/+/master/docs/reference.md#target_cpu
#      Don't forget to set up "NPM_CONFIG_ARCH" and "TARGET_ARCH" accordingly
#      if you pass a custom value for 'target_cpu'.
#  - "ELECTRON_RELEASE" Set it to '1' upload binaries on success.
#  - "NPM_CONFIG_ARCH" E.g. 'x86'. Is used to build native Node.js modules.
#      Must match 'target_cpu' passed to "GN_EXTRA_ARGS" and "TARGET_ARCH" value.
#  - "TARGET_ARCH" Choose from {'ia32', 'x64', 'arm', 'arm64', 'mips64el'}.
#      Is used in some publishing scripts, but does NOT affect the Electron binary.
#      Must match 'target_cpu' passed to "GN_EXTRA_ARGS" and "NPM_CONFIG_ARCH" value.
#  - "UPLOAD_TO_STORAGE" Set it to '1' upload a release to the Azure bucket.
#      Otherwise the release will be uploaded to the GitHub Releases.
#      (The value is only checked if "ELECTRON_RELEASE" is defined.)
#
# The publishing scripts expect access tokens to be defined as env vars,
# but those are not covered here.
#
# AppVeyor docs on variables:
# https://www.appveyor.com/docs/environment-variables/
# https://www.appveyor.com/docs/build-configuration/#secure-variables
# https://www.appveyor.com/docs/build-configuration/#custom-environment-variables

version: 1.0.{build}
build_cloud: electronhq-16-core
image: e-110.0.5415.0
environment:
  GIT_CACHE_PATH: C:\Users\appveyor\libcc_cache
  ELECTRON_OUT_DIR: Default
  ELECTRON_ENABLE_STACK_DUMPING: 1
  ELECTRON_ALSO_LOG_TO_STDERR: 1
  MOCHA_REPORTER: mocha-multi-reporters
  MOCHA_MULTI_REPORTERS: mocha-appveyor-reporter, tap
  GOMA_FALLBACK_ON_AUTH_FAILURE: true
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  PYTHONIOENCODING: UTF-8

  matrix:

    - job_name: Build
    - job_name: Test
      job_depends_on: Build

configuration:
  - Debug
  - Release  

clone_folder: C:\projects\src\electron

# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true

for:

  - matrix:
      only:
        - job_name: Build

    build_script:
      - ps: |
          if ($env:JK_TEST -eq 'test') {
            echo 'YES VAR WORKS $env:JK_TEST'
          } else {
            echo 'NO VAR WORKS: $env:JK_TEST'
          }
          
  - matrix:
      only:
        - job_name: Test

    build_script:
      - ps: |
          if ($env:JK_TEST -eq 'test') {
            echo 'YES VAR WORKS $env:JK_TEST'
          } else {
            echo 'NO VAR WORKS: $env:JK_TEST'
          }