# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
project_id: "fgmr18mx183acim0"

version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.10

platform:
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: python script/bootstrap.py
  - python script/build.py

test_script:
  - node --version
  - npm --version
  - cmd: python script/test.py

build: off
