resources:
  containers:
  - container: arm64v8-test-container
    image: electronjs/build:arm64v8-4549cebcf9a1e4dff317ce3cf910ff9b64867aac
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
