resources:
  containers:
  - container: arm32v7-test-container
    image: ghcr.io/electron/build:arm32v7-c03ffbb65dff64b9778820ce96b56079f91856f8
    options: --shm-size 128m

jobs:
- job: Test_Arm32v7
  container: arm32v7-test-container
  displayName: Test Arm on Arm32v7 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
