resources:
  containers:
  - container: arm32v7-test-container
    image: ghcr.io/electron/build:arm32v7-93f09557547a42070a0c5904aa7ccada8849fe69
    options: --shm-size 128m

jobs:
- job: Test_Arm32v7
  container: arm32v7-test-container
  displayName: Test Arm on Arm32v7 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
