resources:
  containers:
  - container: arm32v7-test-container
    image: ghcr.io/electron/build:arm32v7-5ff37e8103503c55628d996a6f8a76c167d943bf
    options: --shm-size 128m

jobs:
- job: Test_Arm32v7
  container: arm32v7-test-container
  displayName: Test Arm on Arm32v7 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
