resources:
  containers:
  - container: arm64v8-test-container
    image: ghcr.io/electron/build:arm64v8-c03ffbb65dff64b9778820ce96b56079f91856f8
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
