resources:
  containers:
  - container: arm64v8-test-container
    image: ghcr.io/electron/build:arm64v8-93f09557547a42070a0c5904aa7ccada8849fe69
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
