name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      export BUILD_TOOLS_SHA=f7823abb17572e64307fd08bb8587bdc5ca57a09
      npm i -g @electron/build-tools
      e auto-update disable
