name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      echo "GH ACTION IS: $GITHUB_ACTIONS; GITHUB_REF_NAME: $GITHUB_REF_NAME"
      export BUILD_TOOLS_SHA=15a13b8994757b2ada2bc246c22622fbbe94d92d
      npm i -g @electron/build-tools
      e auto-update disable
