version: '3'

services:
  buildtools:
    image: ghcr.io/electron/devcontainer:aeb9a5a20bcb81a026f02c357174c38fa036eea8

    volumes:
      - ..:/workspaces/gclient/src/electron:cached

      - /var/run/docker.sock:/var/run/docker.sock 

    command: /bin/sh -c "while sleep 1000; do :; done"  

    user: builduser

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
