name: Build Linux

on:
  workflow_dispatch:
  push:
  # pull_request:

jobs:
  build:
  # TODO(vertedinde): Change this to main before merge
    uses: electron/electron/.github/workflows/linux-pipeline.yml@gh-actions-build-linux
    with:
      is-release: false
      gn-config: //electron/build/args/testing.gn
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit