name: Build Linux

on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  build:
    uses: ./.github/workflows/linux-pipeline.yml
    with:
      is-release: false
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit
